minor: test

diff --git a/distelli-manifest.yml b/distelli-manifest.yml
--- a/distelli-manifest.yml
+++ b/distelli-manifest.yml
@@ -1,18 +1,18 @@
 # CI is dedicated to verify NoExceptions in Javadoc checks - checks-only-javadoc-error.xml
 checkstyle/checkstyle:
   Build:
-    - command -v jdk_switcher > /dev/null && jdk_switcher use oraclejdk8
-    - git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester
-    - sed -i.'' 's/^guava/#guava/' projects-for-travis.properties
-    - sed -i.'' 's/#spring-framework/spring-framework/' projects-for-travis.properties
-    - sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh
-    - cd ../../ && mvn clean install -Pno-validations
-    - cd contribution/checkstyle-tester
-    - ./launch.sh -Dcheckstyle.config.location=checks-only-javadoc-error.xml
-    - if grep "Got an exception" target/site/checkstyle.html; then
-    -     echo "[ERROR] Exceptions detected"
-    -     exit 1
-    - else
-    -     echo "[INFO] Finished without exceptions"
-    -     exit 0
-    - fi
+    # - command -v jdk_switcher > /dev/null && jdk_switcher use oraclejdk8
+    # - git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester
+    # - sed -i.'' 's/^guava/#guava/' projects-for-travis.properties
+    # - sed -i.'' 's/#spring-framework/spring-framework/' projects-for-travis.properties
+    # - sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh
+    # - cd ../../ && mvn clean install -Pno-validations
+    # - cd contribution/checkstyle-tester
+    # - ./launch.sh -Dcheckstyle.config.location=checks-only-javadoc-error.xml
+    # - if grep "Got an exception" target/site/checkstyle.html; then
+    # -     echo "[ERROR] Exceptions detected"
+    # -     exit 1
+    # - else
+    # -     echo "[INFO] Finished without exceptions"
+    # -     exit 0
+    # - fi
