infra: update for skips for distelli-manifest.yml

diff --git a/distelli-manifest.yml b/distelli-manifest.yml
--- a/distelli-manifest.yml
+++ b/distelli-manifest.yml
@@ -1,6 +1,15 @@
 # CI is dedicated to verify NoExceptions in Javadoc checks - checks-only-javadoc-error.xml
 checkstyle/checkstyle:
   Build:
+    - set -e
+    - SKIP_FILES="appveyor.yml|circle.yml|shippable.yml|.travis.yml|wercker.yml|fast-forward-merge.sh|LICENSE|LICENSE.apache20|README.md|release.sh|RIGHTS.antlr"
+    - SKIP_CI=$(if [[ $(git diff --name-only HEAD HEAD~1 | grep -vE "$SKIP_FILES" | cat | wc -c) > 0 ]]; then echo false; else echo true; fi;)
+    - echo "SKIP_CI="$SKIP_CI
+    - |
+      if [[ $SKIP_CI == 'true' ]]; then
+        echo "[INFO] Build is skipped by SKIP_CI"
+        exit 0;
+      fi
     - command -v jdk_switcher > /dev/null && jdk_switcher use oraclejdk8
     - git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester
     - sed -i.'' 's/^guava/#guava/' projects-for-travis.properties
@@ -9,10 +18,11 @@ checkstyle/checkstyle:
     - cd ../../ && mvn clean install -Pno-validations
     - cd contribution/checkstyle-tester
     - ./launch.sh -Dcheckstyle.config.location=checks-only-javadoc-error.xml
-    - if grep "Got an exception" target/site/checkstyle.html; then
-    -     echo "[ERROR] Exceptions detected"
-    -     exit 1
-    - else
-    -     echo "[INFO] Finished without exceptions"
-    -     exit 0
-    - fi
+    - |
+      if grep "Got an exception" target/site/checkstyle.html; then
+        echo "[ERROR] Exceptions detected"
+        exit 1
+      else
+        echo "[INFO] Finished without exceptions"
+        exit 0
+      fi
