config: update shippable to fail if any survived is found in report

diff --git a/shippable.yml b/shippable.yml
--- a/shippable.yml
+++ b/shippable.yml
@@ -6,28 +6,28 @@ jdk:
 
 env:
   matrix:
-    - PROFILE="-Ppitest-checkstyle-xpath,no-validations"
-    - PROFILE="-Ppitest-checkstyle-filters,no-validations"
+    - PROFILE="-Ppitest-checkstyle-xpath,no-validations"; POST_ACTION=check_survived
+    - PROFILE="-Ppitest-checkstyle-filters,no-validations"; POST_ACTION=check_survived
     - PROFILE="-Ppitest-checks-javadoc,no-validations"
     - PROFILE="-Ppitest-checks-imports,no-validations"
     - PROFILE="-Ppitest-checks-metrics,no-validations"
     - PROFILE="-Ppitest-checks-regexp,no-validations"
-    - PROFILE="-Ppitest-checks-sizes,no-validations"
+    - PROFILE="-Ppitest-checks-sizes,no-validations"; POST_ACTION=check_survived
     - PROFILE="-Ppitest-checks-whitespace,no-validations"
     - PROFILE="-Ppitest-checks-misc,no-validations"
     - PROFILE="-Ppitest-checks-blocks,no-validations"
     - PROFILE="-Ppitest-checks-coding,no-validations"
     - PROFILE="-Ppitest-checks-design,no-validations"
     - PROFILE="-Ppitest-checks-annotation,no-validations"
-    - PROFILE="-Ppitest-checks-header,no-validations"
-    - PROFILE="-Ppitest-checks-modifier,no-validations"
-    - PROFILE="-Ppitest-checks-naming,no-validations"
+    - PROFILE="-Ppitest-checks-header,no-validations"; POST_ACTION=check_survived
+    - PROFILE="-Ppitest-checks-modifier,no-validations"; POST_ACTION=check_survived
+    - PROFILE="-Ppitest-checks-naming,no-validations"; POST_ACTION=check_survived
     - PROFILE="-Ppitest-checks-indentation,no-validations"
-    - PROFILE="-Ppitest-checkstyle-tree-walker,no-validations"
-    - PROFILE="-Ppitest-checkstyle-common,no-validations"
-    - PROFILE="-Ppitest-checkstyle-main,no-validations"
-    - PROFILE="-Ppitest-checkstyle-api,no-validations"
-    - PROFILE="-Ppitest-checkstyle-utils,no-validations"
+    - PROFILE="-Ppitest-checkstyle-tree-walker,no-validations"; POST_ACTION=check_survived
+    - PROFILE="-Ppitest-checkstyle-common,no-validations"; POST_ACTION=check_survived
+    - PROFILE="-Ppitest-checkstyle-main,no-validations"; POST_ACTION=check_survived
+    - PROFILE="-Ppitest-checkstyle-api,no-validations"; POST_ACTION=off_till_resolved
+    - PROFILE="-Ppitest-checkstyle-utils,no-validations"; POST_ACTION=off_till_resolved
     - PROFILE="-Ppitest-checkstyle-gui,no-validations"
 
 branches:
@@ -42,10 +42,19 @@ build:
   ci:
     # we skip PRs and commits that are not for Issues, as pitest is too time consuming
     - |
+      set -e
       SKIP_FILES="appveyor.yml|circle.yml|distelli-manifest.yml|.travis.yml|wercker.yml|fast-forward-merge.sh|LICENSE|LICENSE.apache20|README.md|release.sh|RIGHTS.antlr|intellij-idea-inspections.xml"
       SKIP_CI=$(if [[ $(git diff --name-only HEAD HEAD~1 | grep -vE "$SKIP_FILES" | cat | wc -c) > 0 ]]; then echo false; else echo true; fi;)
       echo "SKIP_CI="$SKIP_CI
+      echo "POST_ACTION="$POST_ACTION
       if [[ $SKIP_CI == 'false' ]];
       then
         mvn $PROFILE clean verify org.pitest:pitest-maven:mutationCoverage;
+
+        if [[ $POST_ACTION == 'check_survived' && $(grep -RE "class='survived'" target/ | cat | wc -l) > 0 ]]; then
+           echo "Survived items:"$(grep -RE "class='survived'" target/ | cat)
+           echo "Survived items found in reports, build will be failed"
+           exit 1
+        fi
+
       fi
